name: villouta.info
favicon: null
layout_spectrum: 0.4114698071498424
typography_spectrum: 0.9041481206659228
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.834701391402632
  lightness: 0.642360799247399
  saturation: 0.7864935579709709
  rhythmicContrast: 0.47899921890348196
purpose: []
